namespace AppiumApp;

public enum KeyCode
{
    KEYCODE_UNKNOWN,
    KEYCODE_MENU,
    KEYCODE_SOFT_RIGHT,
    KEYCODE_HOME,
    KEYCODE_BACK,
    KEYCODE_CALL,
    KEYCODE_ENDCALL,
    KEYCODE_0,
    KEYCODE_1,
    KEYCODE_2,
    KEYCODE_3,
    KEYCODE_4,
    KEYCODE_5,
    KEYCODE_6,
    KEYCODE_7,
    KEYCODE_8,
    KEYCODE_9,
	KEYCODE_VOLUME_UP = 24,
    KEYCODE_VOLUME_DOWN = 25,
    KEYCODE_POWER = 26,
    KEYCODE_CAMERA = 27,
    KEYCODE_CLEAR = 28,
	KEYCODE_SYSRQ = 120,
}